### ISSUE TITLE
Add missing fields to build collector

### ISSUE THREAD

**Issue by aalsabag** [rode/collector-build#7]
There are a few missing/empty fields being sent into Rode that can be extracted from Github or sent in from Jenkins.

Create/Update time
Checksum
Commands
Creator

**Comment by pickjasmine** [comment]
Fields that the UI is using and where it lives within the build occurrences

- Created time: `occurrence.build.provenance.startTime`
- Completed time: `occurrence.build.provenance.endTime`
- Creator: `occurrence.build.provenance.creator`
- Artifacts (optional): `occurrence.build.provenance.builtArtifacts`
  - artifacts use `artifact.names`, `artifact.id`, and `artifact.checksum`, if the property is present so feel free to include any of those
- Source uri (optional): `occurrence.build.provenance.sourceProvenance.context.git.url` and `occurrence.build.provenance.sourceProvenance.context.git.revisionId` if the `git.url` is present
- Logs uri (optional): `occurrence.build.provenance.logsUri`

**Comment by pickjasmine** [comment]
If any of the above are optional and not specified as optional, please let me know and I'll make sure that the UI is handling that correctly.

**Comment by alexashley** [comment]
I think we omitted the create/update time because they should be set by Grafeas:

- [`createTime`](https://github.com/rode/grafeas-elasticsearch/blob/39f9e9645c0ad7b002d867468b45663aa4c46fb5/go/v1beta1/storage/elasticsearch.go#L292-L294)
- [`updateTime`](https://github.com/rode/grafeas-elasticsearch/blob/39f9e9645c0ad7b002d867468b45663aa4c46fb5/go/v1beta1/storage/elasticsearch.go#L428-L431)

And it looks like it does, but maybe with too much precision: `"createTime": "2021-04-16T22:31:32.833636256Z",`

There's also the [`createTime`](https://github.com/rode/collector-build/blob/7a896c1723c64af63f615c6d8e8c9d244ca478c5/server/server.go#L216) on the provenance that the collector does set

**Comment by alexashley** [comment]
Addressed in #9, which added most of these fields (with the exception of `checksum` for artifacts and `commands`)
